### ISSUE TITLE
希望添加 iOS 的 xxx.app 解析，可用于 Github Actions 上解析应用信息

### ISSUE THREAD

**Issue by droplet-js** [icyleaf/app-info#75]
--no-codesign 是无签名打包，不会打包出 IPA 文件，只会打包出 xxx.xcarchive 文件

```yaml
name: Build Android/iOS

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - main

jobs:
  build-ipa:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Build iOS IPA
        run: |
          flutter clean
          flutter pub get
          echo "不混淆Dart"
          flutter build ipa --release --target lib/main.dart --no-codesign --export-method app-store
          # echo "混淆Dart"
          # flutter build ipa --release --obfuscate --split-debug-info=obfuscate/symbols --target lib/main.dart --no-codesign--export-method app-store
      - name: Export Build Settings
        run: |
          pushd ios
          xcodebuild -showBuildSettings -json > build-settings.json
          popd
#      - name: Parse IPA Info
#        uses: k1LoW/github-script-ruby@v2
#        with:
#          gemfile: |
#            source 'https://rubygems.org'
#            gem 'json'
#            gem 'app-info'
#          script: |
#            require 'json'
#            require 'app-info'
#
#            buildSettings = JSON.parse(File.read('ios/build-settings.json')).detect {|e| e['target'] == 'Runner'}['buildSettings']
#            ipaFile = "build/ios/ipa/#{buildSettings['PRODUCT_NAME']}.ipa"
#
#            ipaInfo = AppInfo.parse(ipaFile)
#            File.write('ios/ipa-info.json', { app_name: ipaInfo.name, bundle_id: ipaInfo.bundle_id }.to_json)
#      - name: Cat IPA Info
#        run: |
#          cat ios/ipa-info.json
```
